### ISSUE TITLE
[Bookcase#02] 서재 CSS 퍼블리싱

### ISSUE THREAD

**Issue by sharpcoder312** [TeamBookTez/booktez-client#17]
## 종류

ISSUE 종류를 선택하세요 (`[ ]` 안에 `x` 표시, `[x]`)

- [x] Feature (제가 해냈습니다)

## 내용

- 서재 페이지 기능을 제외한 뷰 CSS 퍼블리싱 작업

## 체크리스트

- [x] 칸반보드에 있는 에픽 번호를 이슈 이름에 명시
  - EX `[E#00] 테스트 이슈`
- [x] Assignees / Labels / Projects 선택
- [x] 스타일드 컴포넌트 분리
- [x] 재사용성을 위한 컴포넌트 분리
- [x] 기본 CSS 퍼블리싱

**Comment by joohaem** [comment]
상언아 체크리스트 체크는 언제 하게 ~~ /?
